name: Update Index HTML

on:
  push:
    branches:
      - main  # Cambia 'main' por tu rama principal si es diferente

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update index.html
        run: echo "<h1>Updated with CI/CD!</h1>" > index.html

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}  
        run: |
          git config --global user.email "actions@dannyvas23@gmail.com"
          git config --global user.name "Danny"
          git add index.html
          git commit -m "Actualizacion index.html with CI/CD"
          git push
